### PR TITLE
Changing WinForms and WPF to use WebView2

### PR DESCRIPTION
**Pull request by jmiddour**
### Changes

Due to the Toolkit WebView package being deprecated, starting with .Net 5.0 the sdk should use the WebView2 control instead.
This PR is an implementation of this change.

In addition, SDK project style test projects have been added to ease testing of .Net 5.0+ targets.  I left the existing test applications alone to keep easy testing of .Net Framework targets.  

Since the WebView2 control requires the WebView2 runtime to be installed on the users' machine, this should probably be considered a breaking change.

### References

Please include relevant links supporting this change such as a:
#169 

### Testing

This change can be tested via the interactive test applications.

### Checklist

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
- [x] All existing and new tests complete without errors
- [x] All code guidelines in the [CONTRIBUTING documentation](../CONTRIBUTING.md) have been run/followed

### CODE REVIEW

**Comment by frederikprijck** [comment]
Thanks for the PR.

I am a bit confused why you are replacing the existing WebView with WebView2 instead of adding WebView2 as a separate browser, as being described in https://community.auth0.com/t/howto-use-the-auth0-oidcclient-winforms-sdk-with-edge-chromium-webview2/57746 ?

If we would do it as a separate browser, we would not directly impact our existing users, and they have the option to opt-in to use WebView2 when they see fit.

On top of that, it would probably also enable adding WebView2 in a non-breaking change way.

**Comment by jmiddour** [comment]
I had 2 reasons for removing the old webview.

First, the Microsoft.Toolkit.Forms.UI.Controls.WebView package has been deprecated and is no longer supported.  The package owners recommend moving away from that package as soon as feasible.

Second, referencing (even indirectly) Microsoft.Toolkit.Forms.UI.Controls.WebView in a project that targets .Net 5.0 or higher results in a compile error.

If you'd prefer that I change the PR to drop support for .Net 5.0+, I can certainly do so.  It will need to be changed as soon as .netcoreapp3.1 target is no longer under active support -- currently scheduled for December 3, 2022.  I think it _should_ be changed when .Net 6 -- the next LTS version of .Net -- is released (scheduled for this November).

**Comment by frederikprijck** [comment]
> First, the Microsoft.Toolkit.Forms.UI.Controls.WebView package has been deprecated and is no longer supported. The package owners recommend moving away from that package as soon as feasible.

A package being deprecated is one thing. Our SDK needs a deprecation strategy, which does not mean getting rid of it.
We want to tell our users it is being deprecated, but they can still use it but we recommend (not enforce) them to move to use an alternative.

> Second, referencing (even indirectly) Microsoft.Toolkit.Forms.UI.Controls.WebView in a project that targets .Net 5.0 or higher results in a compile error.

Can't we get away with this by not including this reference in .NET 5 using conditions?

```
<PackageReference Include="Microsoft.Toolkit.Wpf.UI.Controls.WebView" Condition="'$(TargetFramework)' == 'netcoreapp3.1'">
     <Version>6.1.1</Version>
</PackageReference>
```

**Comment by jmiddour** [comment]
I just did a quick test to confirm the conditional access worked.  It did, so I will update the implementation to have both browsers.  May take me a couple days to get done.

**Comment by jmiddour** [comment]
> A package being deprecated is one thing. Our SDK needs a deprecation strategy, which does not mean getting rid of it.
>We want to tell our users it is being deprecated, but they can still use it but we recommend (not enforce) them to move to use an alternative.

I'd just like to add that I understand your reasoning for not wanting to remove the deprecated package.  As a platform and sdk provider, you have to balance everything against the customer experience.

My work tends to be extremely risk adverse when dealing with external code (especially related to authentication and authorization in any way).  As a result, we deal with breaking changes so often we include it in our planning.

**Comment by frederikprijck** [comment]
> I'd just like to add that I understand your reasoning for not wanting to remove the deprecated package. As a platform and sdk provider, you have to balance everything against the customer experience.

> My work tends to be extremely risk-averse when dealing with external code (especially related to authentication and authorization in any way). As a result, we deal with breaking changes so often we include it in our planning.

Yes, I understand that. But as we serve more users but only you, there will be people that need more time to get on the WebView2 train. Therefore, we should guide people to move away from WebView1, without forcing them by removing WebView1 and breaking their application only because we also wanted to support WebView2.

Either way, supporting WebView2 and dropping support for WebView1 are two different things. Let us focus on adding support for WebView2 here in an opt-in way.

> And just for my info, are you planning to keep the old webview in the framework version after netcoreapp3.1 goes out of support?

Probably not, but that is still a long time ahead :) And should not be of any relevance here.

**Comment by frederikprijck** [comment]
Closing this for now. Happy to reopen of there has been any development here.

**Pull request closed without merging**
