### PR TITLE
Remove ToLower on callbackURL for android

### PR DESCRIPTION
**Pull request by CSkoubo**
### Changes
Removed ToLower() on callbackURL for android as package names are case sensitive. I spent 1 day trying to figure out why my callbacks didn't work, as my package name contains capital letters. So following guides and normal ways of making intent filters for android doesn't work with this library in such cases.
Calling ToLower() within the sdk is misleading and shouldn't be done.

changes are done in Auth0Client.cs on android

### Testing

I have not tested this, besides lowering my own scheme and dataprefix in the intentfilter.

- [ ] This change adds unit test coverage
- [ ] This change adds integration test coverage
- [ ] This change has been tested on the latest version of the platform/language or why not

### Checklist

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
- [x] All existing and new tests complete without errors
- [x] All code guidelines in the [CONTRIBUTING documentation](../CONTRIBUTING.md) have been run/followed

### CODE REVIEW

**Comment by lbalmaceda** [comment]
@CSkoubo The problems appear when your app that uses a package name with uppercase letters registers an Intent Filter in the `AndroidManifest.xml` file using a non-lower-case scheme. Android doesn't allow uppercase chars on the scheme of an Intent Filter. It is _not_ normal to use an uppercase package name for your application, however no one forbids it. 😄 

I understand that the line that you've changed wasn't preventing that either, but only normalizing the output. I assume (it wasn't specified) you ran into a "Callback URL not whitelisted" error. At least for Auth0, callback URLs are _only_ case-insensitive for the scheme and host parts but are case-sensitive for the path. So if you whitelisted a different value, the callback would fail. 

Whenever you run into an Auth0 error page I suggest you click the "show details" link and read the actual error message as that might give you a better hint to debug the issue. In the case of a URL whitelisting error, it would show _what_ was the URL that the browser just tried to call and failed. 👍 

@damieng I guess the docs/quickstarts need some update? Ultimately, the diff on the PR can be changed to only lower the scheme part of the final callback URL.

**Comment by damieng** [comment]
We've had some of this discussion already in https://github.com/auth0/auth0-oidc-client-net/pull/85

I think ToLowering the protocol might be the safest option.  Will dig into this and test this week.

**Comment by CSkoubo** [comment]
> @CSkoubo The problems appear when your app that uses a package name with uppercase letters registers an Intent Filter in the `AndroidManifest.xml` file using a non-lower-case scheme. Android doesn't allow uppercase chars on the scheme of an Intent Filter. It is _not_ normal to use an uppercase package name for your application, however no one forbids it. 😄
> 
> I understand that the line that you've changed wasn't preventing that either, but only normalizing the output. I assume (it wasn't specified) you ran into a "Callback URL not whitelisted" error. At least for Auth0, callback URLs are _only_ case-insensitive for the scheme and host parts but are case-sensitive for the path. So if you whitelisted a different value, the callback would fail.
> 
> Whenever you run into an Auth0 error page I suggest you click the "show details" link and read the actual error message as that might give you a better hint to debug the issue. In the case of a URL whitelisting error, it would show _what_ was the URL that the browser just tried to call and failed. 👍
> 
> @damieng I guess the docs/quickstarts need some update? Ultimately, the diff on the PR can be changed to only lower the scheme part of the final callback URL.

I do get its not normal to use uppercase in packagename - however it is allowed. So the code should not do any asumptions that people always have lower case.

From my testing it is allowed to register intentfilters with uppercase letters. I ran the following command: `adb shell am start -W -a android.intent.action.VIEW -d "com.mycompany.Myapp://domain.eu.auth0.com/android/com.mycompany.Myapp/callback"  ` it started my activity and hit OnNewIntent. However if i used a lowercase packagename scheme and dataprefix it didn't find any intent filters, as it is registered with uppercase - which was my real issue.

My Auth0 was succesful and the log also states a success login. But the callback on the device fails, as there is no intentfilter registered in my case for lowercase, as i have a uppercase letter in my packagename.

**Comment by damieng** [comment]
I think for the 2.4.2 release we can't introduce the breaking change that removing ToLower would cause existing customers but I agree long-term it should be removed for consistency.

What we can do in the 2.4.2 release is give you the ability to pass a uri to the auth0client that overrides our calculated and tolowered version with your own uri passed as-is.

Does that unblock you for now?

**Comment by damieng** [comment]
Handling with extra information until 3.0 - https://github.com/auth0/auth0-oidc-client-net/pull/88

**Comment by damieng** [comment]
Have manually performed this on the 3.0 branch.

**Comment by CSkoubo** [comment]
It didn't block me, but wasted many of my hours. As its a hidden and unexpected "feature". I would recommend you write about this in the android documentation.

**Pull request closed without merging**
