### PR TITLE
Fixed Auth0Client to allow overriding of RedirectUri.

### LINKED ISSUE #84: Impossible to set custom uri callback for iOS+Android
### Description

Unable to set custom callback URL callback for Auth0.OidcClient.iOS and Auth0.OidcClient.Android (possibly others).
If you setup your Auth0ClientOptions like this: 
```
var callback = "com.myapp.thing://somedomain/ios/com.myapp.thing/callback";
var clientOptions = new Auth0ClientOptions()
{
    ClientId = ...,
    Domain = ...,
    Scope = ...,
    LoadProfile = ...,
    RedirectUri = callback,
    PostLogoutRedirectUri = callback,
};
...
var client = new Auth0Client(clientOptions);
```
In this instance you define the callback uri which gets passed to the constructor of the Auth0Client object. Within the [iOS](https://github.com/auth0/auth0-oidc-client-net/blob/master/src/Auth0.OidcClient.iOS/Auth0Client.cs#L19-L21) and [Android](https://github.com/auth0/auth0-oidc-client-net/blob/master/src/Auth0.OidcClient.Android/Auth0Client.cs#L19-L21) code itself this is blown away making it impossible to set custom uri callbacks.

The comments for RedirectUri do say that "This should only be done in exceptional circumstances", but practically its impossible to use a custom RedirectUri.

In our particular case our Android app works as it has a .ToLower() on the end of that call bar uri it generates. For iOS we are unable to change our bundle name to be lowercase. That doesn't change the fact that the code is just broken.

The .ToLower() can actually be traced back to a pre2.0 build as listed in the top comment of #10

### Prerequisites

- [x] I have checked the [README documentation](https://github.com/auth0/auth0-oidc-client-net/blob/master/README.md).
- [ ] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.
- [x] I have checked for related or duplicate [Issues](https://github.com/auth0/auth0-oidc-client-net/issues) and [PRs](https://github.com/auth0/auth0-oidc-client-net/pulls).
- [ ] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).
- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).
- [x] I am reporting this to the correct repository.

### Environment

Using oidc client v2.4 for iOS and 2.4.1 for Android in an Xamarin.Forms application.

### PR DESCRIPTION
**Pull request by beeradmoore**
### Changes

Made iOS match Android by using the lowercase bundle ID as default callback uri.
Updated nuspec and AssemblyInfo for iOS and Android projects to 2.4.2.

### References

Fixes #84

### Testing

Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors. 

- [ ] This change adds unit test coverage
- [ ] This change adds integration test coverage
- [x] This change has been tested on the latest version of the platform/language or why not

### Checklist

- [ ] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [ ] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
- [ ] All existing and new tests complete without errors
- [ ] All code guidelines in the [CONTRIBUTING documentation](../CONTRIBUTING.md) have been run/followed

### CODE REVIEW

**Comment by damieng** [comment]
I think adding ToLower on the iOS while would be great for consistency would break people already using the library?  If that's the case we'd have to remove that part for now and save that call for a the next major release number.

Rest of it looks great.

**Comment by beeradmoore** [comment]
The ToLower would possibly break it for some users, or would solve issues for some users at the same time.

I don't use the Auth0 portal, another team I work with generated our Auth0 app and access. What they requested from was what is our app bundle ID and then they generated the callback URL for us and told us to put this into the app. It was only after an update the iOS version broke (not because of ToLower, but because 2.4.0 does not accept ReturnUri)

Personally I'd always user lowercase bundle IDs but I didn't generate this one. They are case sensitive though, so the best option would be to not ToLower any of them by default. But again, this will this now (minor) break for some Android users. 

On the flip side, are people with 2.4.0+ just working around this issue by adjusting the callback uri on the Auth0 website until it works?

Either way I'll restore it to what it was. But I think for a 3.0 release the ToLower should be removed.

**Comment by damieng** [comment]
Right now master is actually prepared for a breaking 3.0 release which was subsequently delayed as we wanted IdentityClient to also hit 3.0 before bumping.

I'm going to consider whether we bundle this and #86 onto a 2.4.2 release based on a new branch off the 2.4.1 tag.

**Comment by beeradmoore** [comment]
All good. As a work around I built my own nugets locally and bundled that in my app to work around the issue.

**Pull request merged**
