### PR TITLE
Update to version 2.7.0 of IdentityModel.OidcClient

### PR DESCRIPTION
**Pull request by cdesewell**
Build:

https://ci.appveyor.com/project/leastprivilege/identitymodel-oidcclient2

Changes:

https://github.com/IdentityModel/IdentityModel.OidcClient2/pull/69

### CODE REVIEW

**Comment by jerriep** [comment]
@cdesewell I merged the changes.

I had a look at the issue you referenced, but I do not see how those particular changes will benefit you over here since we are hiding away the implementation of `IdentityModel.OidcClient` in our own library.

Is there something you require from us to change as well?

**Comment by jerriep** [comment]
Unless what you're after is the changes to `LoginResult` et al?

**Comment by cdesewell** [comment]
@jerriep Yes im looking to override the result classes.

**Comment by jerriep** [comment]
Ok, cool.

I'll hopefully release a new version in the next day or two, but there should be nothing preventing you from using IdentityModel.OidcClient v2.7 in your project now already.

**Comment by cdesewell** [comment]
@jerriep Amazong Thanks. Just a heads up, Ill also be bringing this change: https://github.com/IdentityModel/IdentityModel.OidcClient2/pull/70

**Pull request merged**
