### PR TITLE
New AndroidX SKU

### PR DESCRIPTION
**Pull request by damieng**
This PR takes the code changes from #146 and puts them in a separate AndroidX assembly/NuGet package so that both Android and AndroidX consumers can continue side by side without interference.

### CODE REVIEW

**Comment by lbalmaceda** [comment]
~2 years ago AndroidX was born to replace support libraries, with `jetifier` as a tool that helps transition those in the middle ground. If we have a package that is already using AndroidX, I don't think we should add back the support for old libraries on a different package. Not to mention this is yet one more variant to maintain. 😕

**Comment by damieng** [comment]
@lbalmaceda This doesn't add-back non-X Android. It adds AndroidX alongside regular android so nobody gets left out.

There isn't actually any "new" code here, it's basically just a way of recompiling the existing Android code into an AndroidX nuget. If there's a worry about code duplication I could probably rework this so it re-used the same android files with a #if around the correct namespacing.

**Comment by beeradmoore** [comment]
@damieng , are there any nightly builds we can test this with to help get it merged in and deployed? Or build local dll and just try it like that?

**Comment by damieng** [comment]
You should be able to check out this branch and build a dll to try.

I spoke to the team out of band about their concerns I think I can get
those addressed in the next 24 hours.

**Comment by damieng** [comment]
Okay, have updated the PR. Once CI goes green I think we're good to merge. Were you able to try it @beeradmoore ?

**Comment by beeradmoore** [comment]
I got moved off AndroidX updates onto other projects at work so I wasn't able to get the ball rolling on testing this unfortunately.

**Pull request merged**
